"""
ZULU PARTS CATALOG  —  searchable supplier parts reference for the /jdstock endpoint
=====================================================================================
Loads the cache built by ingest_parts_catalog.py (zulu_parts_catalog.json — git-ignored,
regenerated by hand whenever a new supplier catalog is dropped in). Absent file = empty
catalog, same graceful-fallback style zulu_server.py already uses for zulu_knowledge/
zulu_private imports, so a fresh checkout with no catalog yet still runs fine.

Scoring uses whole-word matching (not substring counting) for the same reason it was just
fixed in zulu_private.py's _kw_score: a part name/number query shouldn't score a false hit
because a query word happens to appear inside an unrelated word.
"""
import json
import os
import re

_HERE = os.path.dirname(os.path.abspath(__file__))
_CATALOG_PATH = os.path.join(_HERE, "zulu_parts_catalog.json")

_STOPWORDS = {
    "the", "a", "an", "is", "are", "was", "were", "be", "been", "and", "or", "of", "to", "in",
    "on", "for", "what", "which", "who", "how", "why", "when", "where", "my", "me", "i", "you",
    "your", "it", "this", "that", "do", "does", "did", "with", "at", "as", "from", "about",
    "our", "us", "we", "he", "his", "him", "not", "do", "have", "has", "any",
}


def _load_catalog():
    try:
        with open(_CATALOG_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return []


PARTS = _load_catalog()


def parts_catalog_count():
    return len(PARTS)


def _row_text(row):
    return " ".join(str(row.get(f, "")) for f in ("name", "part_no", "category", "notes"))


def _kw_score(text, words):
    tl = text.lower()
    return sum(len(re.findall(r"\b" + re.escape(w) + r"\b", tl)) for w in words)


def _format_row(row):
    bits = [row.get("name", "").strip()]
    if row.get("part_no"):
        bits.append(f"(part no. {row['part_no']})")
    if row.get("category"):
        bits.append(f"— {row['category']}")
    if row.get("price"):
        bits.append(f"— Rs {row['price']:g}" if isinstance(row["price"], float) else f"— Rs {row['price']}")
    if row.get("notes"):
        bits.append(f"[{row['notes']}]")
    bits.append(f"(source: {row.get('source_file', '?')})")
    return " ".join(b for b in bits if b)


def parts_catalog_search(query, k=5, min_score=1):
    """Return up to k formatted catalog lines most relevant to query. Empty list if the
    catalog hasn't been ingested yet, or nothing scores — caller should treat that as
    'not in the supplier catalog' rather than retry with a lower bar."""
    if not PARTS:
        return []
    words = [w for w in re.findall(r"[a-z0-9']{2,}", (query or "").lower()) if w not in _STOPWORDS]
    if not words:
        return []
    scored = [(_kw_score(_row_text(row), words), row) for row in PARTS]
    scored = [(sc, row) for sc, row in scored if sc >= min_score]
    scored.sort(key=lambda x: x[0], reverse=True)
    return [_format_row(row) for _sc, row in scored[:k]]
